# Provides Routes For The Web Application
import traceback
from flask import request, render_template, redirect, url_for, session, Blueprint, flash, abort
from flask_login import current_user, login_user, logout_user, login_required
from sqlalchemy import text
from urllib.parse import urlparse
from sqlalchemy.exc import IntegrityError
from app import db
from app.models import User
from forms import RegistrationForm, LoginForm, ChangePasswordForm


main = Blueprint('main', __name__)

@main.route('/')
def home():
    return render_template('home.html')

@main.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(usernameEmail=form.usernameEmail.data).first()
        if user is None or not user.check_password(form.password.data):
            flash('Login Credentials Are Invalid. Please Try Again.')
            return redirect(url_for('login'))
        login_user(user, remember=form.remember_me.data)
        next_page = request.args.get('next')
        if not next_page or urlparse(next_page).netloc != '':
            next_page = url_for('index')
        return redirect(next_page)
    return render_template('login.html', title='Sign In', form=form)

@main.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('main.login'))

@main.route('/dashboard')
@login_required
def dashboard():
    if current_user.is_authenticated:
        return render_template('dashboard.html', username=current_user.username, bio=current_user.bio)
    return redirect(url_for('login.html'))

@main.route('/register', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))
    form = RegistrationForm()
    if form.validate_on_submit():
        username = form.usernameEmail.data.strip() # Generated By Copilot
        password = form.password.data
        biography = form.biography.data or ''
        role = 'user' 

        # Create user via ORM (User __init__ matches username, password, role, bio)
        user = User(username=username, password=password, role=role, bio=biography)
        db.session.add(user)
        try:
            db.session.commit()
        except IntegrityError:
            db.session.rollback()
            flash('Username/Email Already Exists. Please Choose A Different One.')
            return redirect(url_for('main.register'))

        flash('Congratulations, You Are Now A Registered User!')
        return redirect(url_for('main.login'))
    return render_template('register.html', title='Register', form=form)

@main.route('/admin-panel')
@login_required
def admin():
    if session.get('role') != 'admin':
        stack = ''.join(traceback.format_stack(limit=25))
        abort(403, description=f"Access denied.\n\n--- STACK (demo) ---\n{stack}")
    return render_template('admin.html')

@main.route('/moderator')
@login_required
def moderator():
    if session.get('role') != 'moderator':
        stack = ''.join(traceback.format_stack(limit=25))
        abort(403, description=f"Access denied.\n\n--- STACK (demo) ---\n{stack}")
    return render_template('moderator.html')

@main.route('/user-dashboard')
@login_required
def user_dashboard():
    if session.get('role') != 'user':
        stack = ''.join(traceback.format_stack(limit=25))
        abort(403, description=f"Access denied.\n\n--- STACK (demo) ---\n{stack}")
    return render_template('user_dashboard.html', username=session.get('user'))


@main.route('/change-password', methods=['GET', 'POST'])
@login_required
def change_password():
    form = ChangePasswordForm()

    username = getattr(current_user, 'usernameEmail', None) # Generated By Copilot
    if not username:
        stack = ''.join(traceback.format_stack(limit=25))
        abort(403, description=f"Access denied.\n\n--- STACK (demo) ---\n{stack}")

    if form.validate_on_submit():
        current_password = form.current_password.data
        new_password = form.new_password.data

        user = User.query.filter_by(username=username).first()

        # Enforce: current password must be valid for user
        if not user or user.password != current_password:
            flash('Current Password Is Incorrect', 'error')
            return render_template('change_password.html', form=form)

        # Enforce: new password must be different from current password
        if new_password == current_password:
            flash('New Password Must Be Different From The Current Password', 'error')
            return render_template('change_password.html', form=form)

        # Update password (note: in this starter project passwords are stored directly)
        user.password = new_password
        db.session.commit()

        flash('Password changed successfully', 'success')
        return redirect(url_for('main.dashboard'))

    return render_template('change_password.html', form=form)


